config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'unclassifiable', to: 'pages#unclassifiable', as: :unclassifiable
  get 'wouldyou', to: 'pages#wouldyou', as: :wouldyou
  get 'contact', to: 'pages#contact', as: :contact
  get '/hotels', to: 'pages#hotels'
  get '/buyers', to: 'pages#buyers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rendezvous - International Hotel Forum</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/buyers.html.erb
<div class="white-space"></div>
<div class="buyers">
  <%= cl_video_tag("RDV_LISBON_BUYERS_1_edlzv3", loop: true, autoplay: true, muted: true, controls: true) %>

  <h2>Our Recipe</h2>
  <div class="hotels_recipe_content">
    <div class="hotels_recipe_content_left">
      <div class="hotels-card">
        <div class="hotels-card_image">
          <%= image_tag 'icon-1.png' %>
        </div>
        <div class="hotels-card_content">
          <h4>Our RENDEZVOUS IHF</h4>
          <h6>A friendly welcome reception & dinner on the arrival day attended by all VIP Buyers and Hoteliers</h6>
        </div>
      </div>
      <div class="hotels-card">
        <div class="hotels-card_image">
          <%= image_tag 'icon-3.png' %>
        </div>
        <div class="hotels-card_content">
          <h4>One to One meetings</h4>
          <h6>A minimum of 40 pre-scheduled meetings organized between European VIP clients coming from corporate companies, MICE & Incentives agencies and European luxury 5 stars hotels with leaders in Corporate Event management and Location Finders - VIP Contacts</h6>
        </div>
      </div>
    </div>
    <div class="hotels_recipe_content_right">
      <div class="hotels-card">
        <div class="hotels-card_image">
          <%= image_tag 'icon-2.png' %>
        </div>
        <div class="hotels-card_content">
          <h4>2 surprise group lunches</h4>
          <h6>Both lunches attended by VIP buyers and Hoteliers</h6>
        </div>
      </div>
      <div class="hotels-card">
        <div class="hotels-card_image">
          <%= image_tag 'icon-4.png' %>
        </div>
        <div class="hotels-card_content">
          <h4>2 networking dinners</h4>
          <h6>One networking and Gala dinner attended by all VIP buyers and Hoteliers</h6>
        </div>
      </div>
      <div class="hotels-card">
        <div class="hotels-card_image">
          <%= image_tag 'icon-5.png' %>
        </div>
        <div class="hotels-card_content">
          <h4>1 afternoon team building activity</h4>
          <h6>Attended by all VIP buyers and Hoteliers</h6>
        </div>
      </div>
    </div>
  </div>
  <div class="hotels_recipe">
    <h2>What's in the Package?</h2>
    <div class="hotels_recipe_content">
      <div class="hotels_recipe_content_left">
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-6.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>3 Nights</b> of accomodation at the Forum’s Hotel</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-7.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 Full access</b> to all benefits of our RENDEZ VOUS IHF B2B Recipe</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-8.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 RENDEZ VOUS IHF 2020 Magazine Profile</b> of you and your represented Hotel / Hotel Group</h6>
          </div>
        </div>
      </div>
      <div class="hotels_recipe_content_right">
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-8.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 RENDEZ VOUS IHF 2020 Magazine Profiles</b> of all attending Luxury Hotels & VIP Buyers</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-9.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 Memorable Business Investment</b> turned into multiple Long Term Partnerships</h6>
          </div>
        </div>
      </div>
    </div>
  </div>

    <a class="pink-button" onclick="openForm()">Register</a>

</div>
<div class="registration-popup">
  <div class="registration-content">
    <a href="javascript:void(0)" class="closebtn registration-content_close" onclick="closeForm()">&times;</a>
    <h4>Registration Form</h4>
    <p>Please make sure to fill out all details. We will call you at the earliest in order to discuss your attendance.</p>
    <form id="fs-frm" name="survey-form" accept-charset="utf-8" action="https://formspree.io/meganne@recallagency.com" method="post">
        <input type="text" name="name" id="full-name" placeholder="First and Last Name" required="">
        <input type="text" name="company" id="company" placeholder="Company Name" required="">
        <input type="text" name="companysite" id="companysite" placeholder="Company URL(www)" required="">
        <input type="text" name="country" id="country" placeholder="Country" required="">
        <input type="email" name="_replyto" id="email-address" placeholder="Email Address" required="">
        <input type="text" name="jobtitle" id="jobtitle" placeholder="Job Title" required="">
        <input type="text" name="phone" id="phone" placeholder="(Area Code) + Phone Number" required="">
        <fieldset id="fs-frm-selects">
          <label for="timely">1. You are a:</label>
          <select name="timely" id="timely" required="">
            <option value="Choose" selected="" disabled="">Choose</option>
            <option value="1">Buyer</option>
            <option value="3">Exhibitor</option>
          </select>
          <label for="timely">2.If you are a buyer, here are some choices</label>
          <select name="quality" id="quality" required="">
            <option value="Choose" selected="" disabled="">Choose</option>
            <option value="1">Mice</option>
            <option value="3">Leisure</option>
            <option value="5">Other</option>
          </select>
        </fieldset>
        <label for="message">Additional Comments</label>
        <textarea rows="3" name="message" id="message" placeholder="Text to Type" required=""></textarea>
        <input type="hidden" name="_subject" id="email-subject" value="Survey Responses">
      <input class="red-button" type="submit" value="Submit">
    </form>
  </div>
</div>
<script>
  const openForm = () => {
    document.querySelector(".registration-popup").style.display = "block";
  };

  const closeForm = () => {
    document.querySelector(".registration-popup").style.display = "none";
  };
</script>

app/views/pages/contact.html.erb
<div class="white-space"></div>
<div class="contact">

  <div class="contact_first">
    <%= image_tag 'white-logo.png', class: "contact-logo" %>
    <h3>Contact Our Team</h3>
  </div>
  <div class="contact_second">
    <div class="contact_second_first-row">
      <div class="avatar">
        <%= image_tag 'alexandre.png' %>
        <h4>Alexandre Olive</h4>
        <h5>Founder</h5>
        <h6><a href="mailto: alexandre@rendezvous-ihf.com" style="color: white;">alexandre@rendezvous-ihf.com</a></h6>
      </div>
      <div class="avatar">
        <%=  image_tag 'estelle.png' %>
        <h4>Estelle Bernière</h4>
        <h5>European Office Manager</h5>
        <h6><a href="mailto: saleseurope@rendezvous-ihf.com" style="color: white;">saleseurope@rendezvous-ihf.com</a></h6>
      </div>
      <div class="avatar">
        <%= image_tag 'pearl.png' %>
        <h4>Pearl Vedere</h4>
        <h5>Director of Sales</h5>
        <h6><a href="mailto: pearl@rendezvous-ihf.com" style="color: white;">pearl@rendezvous-ihf.com</a></h6>
      </div>
    </div>

    <div class="contact_third" id="cform">
      <a href="#testing" class="contact_third_button"> Contact Us</a>
    </div>
  </div>
</div>

<div id="testing" class="contact-form">
  <div class="contact-form_content">
    <a href="#cform" class="contact-form_close">&times;</a>
    <form action="https://formspree.io/saleseurope@rendezvous-ihf.com" method="POST" id="rdvform"/>
      <h2>#DOBUSINESS</h2>
      <div class="form_first">
        <input type="text" name="name" placeholder="Full Name">
        <input type="company" name="company" placeholder="Company">
        <input type="position" name="position" placeholder="Position">
      </div>
      <div class="form_second">

        <input type="email" name="email" placeholder="Email">

          <select name="buyer" id="rdvform" class="form-control">
            <option value="" disabled selected> I am a:</option>
            <option value="Buyer">Buyer</option>
            <option value="Hotel">Hotel</option>
          </select>

          <select name="edition" id="rdvform" class="form-control">
            <option value="" disabled selected> I am interested in:</option>
            <option value="Lisboa Edition">Lisboa Edition</option>
            <option value="Megève Edition">Megève Edition</option>
            <option value="Cartagena Edition">Cartagena Edition</option>
            <option value="Monaco Edition">Monaco Edition</option>
          </select>
      </div>
      <input type="submit" value="Send" class="form_button">
    </form>
  </div>
</div>

app/views/pages/hotels.html.erb
 <div class="white-space"></div>
 <div class="hotels">
  <div class="hotels_banner">
    <h1>YES I DARE!</h1>
  </div>
  <div class="hotels_recipe">
    <h2>Our Recipe</h2>
    <div class="hotels_recipe_content">
      <div class="hotels_recipe_content_left">
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-1.png' %>
          </div>
          <div class="hotels-card_content">
            <h4>Our RENDEZVOUS IHF</h4>
            <h6>A friendly welcome reception & dinner on the arrival day attended by all VIP Buyers and Hoteliers</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-3.png' %>
          </div>
          <div class="hotels-card_content">
            <h4>One to One meetings</h4>
            <h6>A minimum of 40 pre-scheduled meetings organized between European VIP clients coming from corporate companies, MICE & Incentives agencies and European luxury 5 stars hotels with leaders in Corporate Event management and Location Finders - VIP Contacts</h6>
          </div>
        </div>
      </div>
      <div class="hotels_recipe_content_right">
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-2.png' %>
          </div>
          <div class="hotels-card_content">
            <h4>2 surprise group lunches</h4>
            <h6>Both lunches attended by VIP buyers and Hoteliers</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-4.png' %>
          </div>
          <div class="hotels-card_content">
            <h4>2 networking dinners</h4>
            <h6>One networking and Gala dinner attended by all VIP buyers and Hoteliers</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-5.png' %>
          </div>
          <div class="hotels-card_content">
            <h4>1 afternoon team building activity</h4>
            <h6>Attended by all VIP buyers and Hoteliers</h6>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="hotels_recipe">
    <h2>What's in the Package?</h2>
    <div class="hotels_recipe_content">
      <div class="hotels_recipe_content_left">
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-6.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>3 Nights</b> of accomodation at the Forum’s Hotel</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-7.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 Full access</b> to all benefits of our RENDEZ VOUS IHF B2B Recipe</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-8.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 RENDEZ VOUS IHF 2020 Magazine Profile</b> of you and your represented Hotel / Hotel Group</h6>
          </div>
        </div>
      </div>
      <div class="hotels_recipe_content_right">
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-8.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 RENDEZ VOUS IHF 2020 Magazine Profiles</b> of all attending Luxury Hotels & VIP Buyers</h6>
          </div>
        </div>
        <div class="hotels-card">
          <div class="hotels-card_image">
            <%= image_tag 'icon-9.png' %>
          </div>
          <div class="hotels-card_content">
            <h6><b>1 Memorable Business Investment</b> turned into multiple Long Term Partnerships</h6>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="hotels_recipe">
    <h2>Would you join?</h2>
    <div class="left-card">
      <div class="left-card_image">
        <%= image_tag 'monaco.png' %>
      </div>
      <div class="left-card_content">
        <h4>MONACO</h4>
        <h5>Dates</h5>
        <p><b>October 26 to 29, 2020</b></p>
        <h5>Host Hotel</h5>
        <p><b>Hotel l’Hermitage</b></p>
        <%= link_to contact_path do %>
          <button>JOIN</button>
        <% end %>
      </div>
    </div>
    <div class="right-card">
      <div class="right-card_content">
        <h4>MEGÉVE, FRANCE</h4>
        <h5>Dates</h5>
        <p><b>March 24 to 27, 2020</b></p>
        <h5>Host Hotel</h5>
        <p><b>Les Chalets du Mont d'Arbois, Megève, a Four Seasons Hotel</b></p>
        <%= link_to contact_path do %>
          <button>JOIN</button>
        <% end %>
      </div>
      <div class="right-card_image">
        <%= image_tag 'megeve.png' %>
      </div>
    </div>
  </div>
 </div>

app/views/pages/unclassifiable.html.erb
<div class="white-space"></div>
<div class="unclassifiable">
  <div class="unclassifiable_banner">
    <h1>#UNCLASSIFIABLE</h1>
    <h6>
      There is something unclassifiable in RENDEZ VOUS IHF, a mystery that is never fully understood:
      Creative or  statutory ? Fun or business ? Casual or sophistication ?
      <br><br>
      The success of RENDEZ VOUS IHF comes from this fundamental ambivalence:
      to present hotels and destinations, to create strategic contacts, to generate ROI, to reinvent itself
      constantly and to live unforgettable experiences and emotions,
      without ever becoming “just” a simple fair of the luxury travel.
    </h6>
  </div>
  <div class="unclassifiable_testimonials">
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'testimonial-one.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “From the first time I met Alex listening to his principles of RENDEZ VOUS IHF, to the fun of curating a series of unexpected experiences, to the final meaningful delivery – it was very clear to me – this is the new generation of creating emotional connections between people and destinations that will stay memorable. Simply unclassifiable.”
        </i></p>
        <p><b>
          Joachim Hartl, Area General Manager Iberian Peninsula <br> Hilton Worlwide
        </b></p>
      </div>
    </div>
    <div class="right-testimonial">
      <div class="right-testimonial_content">
        <p><i>
          “RENDEZ VOUS IHF Forum's are awesome, funky, unconventional and strikingly different from any other Forums. Alex and Co go out of their way to always surprise us during the networking events and come up with great innovative ideas. <br><br>
          Not only do they truly understand a buyer's needs but they also know how to have the right balance between scheduled appointments and activities. The concept of working in the morning and networking in the afternoon always in a cool unusual place and in a warm atmosphere, is perfect. All social events are always top class with a wow effect with lots of fun and help us all to connect with people on a higher level. Great Event!”
        </i></p>
        <p><b>
         Ulrike Trader, Senior International Events Manager <br> Bird & Bird
        </b></p>
      </div>
      <div class="right-testimonial_avatar">
        <%= image_tag 'testimonial-two.png' %>
      </div>
    </div>
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'testimonial-three.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “RENDEZ VOUS IHF is the bringing together of that which needs no introduction, the expected that becomes the unexpected, a meeting of ideas and beliefs in the luxury travel world that, as Coco Chanel once said, Luxury is the necessity that begins where necessity ends.”
        </i></p>
        <p><b>
          Yuriy Horovyy, Founder & CEO <br> Almont Group
        </b></p>
      </div>
    </div>
    <div class="right-testimonial">
      <div class="right-testimonial_content">
        <p><i>
          “Having participated in several editions of “Rendez-Vous” over the past years, I can say that you guys curate an event like no other!  Both hotel partners and buyers have the opportunity to do business in a relaxed and friendly atmosphere and experience amazingly different things in each destination the event is held in.   Always raising the bar higher!”
        </i></p>
        <p><b>
          Katya Bauval, Executive Director of Sales & Marketing <br>
          VILA VITA Parc Resort & Spa
        </b></p>
      </div>
      <div class="right-testimonial_avatar">
        <%= image_tag 'testimonial-four.png' %>
      </div>
    </div>
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'testimonial-five.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “My meetings at RENDEZ VOUS IHF have always been brilliant, focused on excellent and sometimes unusual suppliers. Everything ran extremely smoothly and I discovered some fantastic venues first-hand.”
        </i></p>
        <p><b>
          Maarten Brunt, Purchasing Manager Global Events  <br> ATPI
        </b></p>
      </div>
    </div>
    <div class="right-testimonial">
      <div class="right-testimonial_content">
        <p><i>
          “RENDEZ VOUS IHF is a successful creative & funny business connecting concept, taylor made by visionaries and leaders from across industries inspire trends that will shape the future of contemporary travel.”
        </i></p>
        <p><b>
          Marie-Ange Bihouix, Director of Sale Marketing & PR <br>
          Five Seas Hotel Cannes
        </b></p>
      </div>
      <div class="right-testimonial_avatar">
        <%= image_tag 'testimonial-six.png' %>
      </div>
    </div>
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'testimonial-seven.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “RENDEZ VOUS IHF Vienna was a great edition! A right mix between face-to-face meetings with top buyers and unique networking events.
          I would define it as a successful combination of conviviality, professionalism, originality, passion and a pinch of Madness #workhardplayhard "
        </i></p>
        <p><b>
          Anne-Emmanuelle Le Bail, Director of Sales <br>
          Waldorf Astoria and Conrad Hotels & Resorts
        </b></p>
      </div>
    </div>
    <div class="right-testimonial">
      <div class="right-testimonial_content">
        <p><i>
          “Quality networking with the best hotel partners in a creative event.
          RENDEZ VOUS is an inspiration for our work
          Thanks RENDEZ VOUS IHF team!”
        </i></p>
        <p><b>
          Miguel Pinto, General Manager <br> YCON Group
        </b></p>
      </div>
      <div class="right-testimonial_avatar">
        <%= image_tag 'testimonial-eight.png' %>
      </div>
    </div>
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'testimonial-nine.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “My first two rendezvous were fantastic experiences which resulted in great business for the hotel. The intimacy of the event means that you get to feel as though you are part of a family which is amazing.”
        </i></p>
        <p><b>
          Andrew Tabone, International Sales Manager <br> Excelsior Grand Hotel
        </b></p>
      </div>
    </div>
    <div class="right-testimonial">
      <div class="right-testimonial_content">
        <p><i>
          “Materialized business opportunities, first contacts made with decision makers and influencers on both sides of suppliers and buyers and an immediate connection of all the participants thanks to a truly unusual and extremely well designed program.”
        </i></p>
        <p><b>
          Benjamin Caudet, Vice President <br>
          EMEA at ATG Business Travel Management
        </b></p>
      </div>
      <div class="right-testimonial_avatar">
        <%= image_tag 'testimonial-ten.png' %>
      </div>
    </div>
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'testimonial-eleven.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “RENDEZ VOUS IHF is so different, because Alex and his team manage to find unique locations, unique attractions and deliver a oscar worthy show for an entire weekend. That paired with well qulified buyers makes Rendez-Vous a super event!”
        </i></p>
        <p><b>
          Felix Sigel, Head of Sales <br> 25 hours Hotels
        </b></p>
      </div>
    </div>
    <div class="right-testimonial">
      <div class="right-testimonial_content">
        <p><i>
          “Not only amazing personalities at the RENDEZ VOUS INTERNATIONAL HOTEL FORUM, but also undeniably flexible,
          tremendously skilled and out-of-the-box thinking hospitality professionals.
          This can only categorized as: UNCLASSIFIABLE!”
        </i></p>
        <p><b>
          Rick van den Berge, Executive Assistant <br> Euronics International BV
        </b></p>
      </div>
      <div class="right-testimonial_avatar">
        <%= image_tag 'testimonial-twelve.png' %>
      </div>
    </div>
    <div class="left-testimonial">
      <div class="left-testimonial_avatar">
        <%= image_tag 'pestana_testimony.png' %>
      </div>
      <div class="left-testimonial_content">
        <p><i>
          “This Forum was absolutely fantastic, from the moment Rendez Vous Team stepped in to the hotel, till the last moment it was an amazing surprise.
          I definitely recommend the participation on this one-2-one MICE Forum combine with a great programme of networking activities and an original and incredible moments in Lisbon town. Congrats to the entire team for this crazy experience, we were very proud to be chosen to organize and participate on such an amazing event full of good moments and memories”
        </i></p>
        <p><b>
          Mónica Soares, Directora de Vendas Lisboa / Lisbon Sales Director <br> Pestana Palace
        </b></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <p> A production of Recall Agency </p>
  <p>6, place de la Madeleine</p>
  <p>75008 Paris, France</p>
  <%= image_tag 'logo.png', class: "footer_logo" %>
  <div class="footer_label">
    <%= link_to 'Hoxton Digital','https://www.hoxton-digital.com' %>
    <%= link_to 'London Web & App Development','https://www.hoxton-digital.com' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-hoxton">

  <div class="navbar-hoxton_first-section">

    <a href="/">
      <%= image_tag 'logo.png' %>
      <!-- <img src="images/logo.png" alt="logo"> -->
    </a>

    <div class="navbar-hoxton_first-section_content">
      <div class="navbar-hoxton_first-section_content_social-media">
        <%= link_to 'https://www.facebook.com/rendezvousihf' do %>
          <i class="fab fa-facebook"></i>
        <% end %>
        <%= link_to 'https://www.instagram.com/rendezvous_ihf/' do %>
          <i class="fab fa-instagram"></i>
        <% end %>
        <%= link_to 'https://www.linkedin.com/company/rendez-vous-ihf/about/' do %>
          <i class="fab fa-linkedin"></i>
        <% end %>
      </div>

      <div class="navbar-hoxton_first-section_content_events hidden-md hidden-sm hidden-xs">
          <!-- <p> LISBOA - OCTOBER 2019</p> -->
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-hoxton_first-section_hamburger hidden-lg">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-hoxton-dropdown-menu">
          <li><%= link_to 'WELCOME', root_path %></li>
          <li><a href="/unclassifiable.html">UNCLASSIFIABLE</a></li>
          <li><a href="/hotels">HOTELS</a></li>
          <li><a href="/buyers">BUYERS</a></li>
          <li><a href="/contact">CONTACT</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="navbar-hoxton_pink-label">

  </div>

  <div class="navbar-hoxton_second-section hidden-sm hidden-xs hidden-md">
    <%= link_to 'WELCOME', root_path, class: "hidden-xs hidden-sm" %>
    <!-- <a href="/home.html.erb" class="hidden-xs hidden-sm">WELCOME</a> -->
    <a href="/unclassifiable.html" class="hidden-xs hidden-sm">UNCLASSIFIABLE</a>
    <a href="/hotels" class="hidden-xs hidden-sm">HOTELS</a>
    <a href="/buyers" class="hidden-xs hidden-sm">BUYERS</a>
    <a href="/contact" class="hidden-xs hidden-sm">CONTACT</a>
  </div>

</div>